"""added i/o files templates to TaskTyle

Revision ID: 097505daec19
Revises: f0485471fbe6
Create Date: 2016-06-07 14:59:48.011767

"""

# revision identifiers, used by Alembic.
revision = '097505daec19'
down_revision = 'f0485471fbe6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_types', sa.Column('ifiles_template', sa.String(length=1024), nullable=True))
    op.add_column('task_types', sa.Column('ofiles_template', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_types', 'ofiles_template')
    op.drop_column('task_types', 'ifiles_template')
    ### end Alembic commands ###