"""added working group of user

Revision ID: 52bdf12339b2
Revises: 4f894a9d7db2
Create Date: 2017-05-30 11:25:29.555111

"""

# revision identifiers, used by Alembic.
revision = '52bdf12339b2'
down_revision = '4f894a9d7db2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('working_group', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'working_group')
    ### end Alembic commands ###