"""added params to task model

Revision ID: 5b93af201332
Revises: 62dc56a32b70
Create Date: 2016-08-08 17:01:01.699876

"""

# revision identifiers, used by Alembic.
revision = '5b93af201332'
down_revision = '62dc56a32b70'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'n')
    op.add_column('tasks', sa.Column('params', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'params')
    op.add_column('pipelines', sa.Column('n', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###