"""added distr to TaskType

Revision ID: 5e23f85605a5
Revises: 5b93af201332
Create Date: 2016-08-10 14:54:25.968410

"""

# revision identifiers, used by Alembic.
revision = '5e23f85605a5'
down_revision = '5b93af201332'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_types', sa.Column('distr_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_types', 'distr', ['distr_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_types', type_='foreignkey')
    op.drop_column('task_types', 'distr_id')
    ### end Alembic commands ###