"""added n to pipeline model

Revision ID: 62dc56a32b70
Revises: 706b63d95e4f
Create Date: 2016-08-05 15:09:00.738035

"""

# revision identifiers, used by Alembic.
revision = '62dc56a32b70'
down_revision = '706b63d95e4f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('n', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'n')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('n', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('pipelines', 'n')
    ### end Alembic commands ###