"""added n to task model

Revision ID: 706b63d95e4f
Revises: 8eaf33482c09
Create Date: 2016-08-05 12:12:33.160630

"""

# revision identifiers, used by Alembic.
revision = '706b63d95e4f'
down_revision = '8eaf33482c09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('n', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'n')
    ### end Alembic commands ###