"""updated task model

Revision ID: 966b1d57488d
Revises: 097505daec19
Create Date: 2016-06-09 11:48:33.829465

"""

# revision identifiers, used by Alembic.
revision = '966b1d57488d'
down_revision = '097505daec19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('ifiles', sa.String(length=1024), nullable=True))
    op.add_column('tasks', sa.Column('ofiles', sa.String(length=1024), nullable=True))
    op.add_column('tasks', sa.Column('trf', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'trf')
    op.drop_column('tasks', 'ofiles')
    op.drop_column('tasks', 'ifiles')
    ### end Alembic commands ###