"""Added timestamps to pipelint

Revision ID: bb2bd0a8c95a
Revises: f7208a6fdec4
Create Date: 2016-08-02 15:01:01.587503

"""

# revision identifiers, used by Alembic.
revision = 'bb2bd0a8c95a'
down_revision = 'f7208a6fdec4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('creation_time', sa.DateTime(), nullable=True))
    op.add_column('pipelines', sa.Column('modification_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'modification_time')
    op.drop_column('pipelines', 'creation_time')
    ### end Alembic commands ###