"""updated Pipeline model

Revision ID: e808ff772420
Revises: f4a400b207a1
Create Date: 2016-06-28 13:42:28.146994

"""

# revision identifiers, used by Alembic.
revision = 'e808ff772420'
down_revision = 'f4a400b207a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('status', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'status')
    ### end Alembic commands ###