"""added encode_commands flag

Revision ID: eef5682e45eb
Revises: c789ecdb563c
Create Date: 2017-04-12 15:51:49.935504

"""

# revision identifiers, used by Alembic.
revision = 'eef5682e45eb'
down_revision = 'c789ecdb563c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('encode_commands', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'encode_commands')
    ### end Alembic commands ###