"""updated Pipeline model

Revision ID: f4a400b207a1
Revises: 3d21a9e6821c
Create Date: 2016-06-21 16:27:08.211713

"""

# revision identifiers, used by Alembic.
revision = 'f4a400b207a1'
down_revision = '3d21a9e6821c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('finish_task_id', sa.Integer(), nullable=True))
    op.add_column('pipelines', sa.Column('init_task_id', sa.Integer(), nullable=True))
    op.add_column('pipelines', sa.Column('merge_task_id', sa.Integer(), nullable=True))
    op.add_column('pipelines', sa.Column('post_task_id', sa.Integer(), nullable=True))
    op.add_column('pipelines', sa.Column('pre_task_id', sa.Integer(), nullable=True))
    op.add_column('pipelines', sa.Column('prun_task_id', sa.Integer(), nullable=True))
    op.add_column('pipelines', sa.Column('split_task_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'pipelines_ibfk_4', 'pipelines', type_='foreignkey')
    op.drop_constraint(u'pipelines_ibfk_5', 'pipelines', type_='foreignkey')
    op.drop_constraint(u'pipelines_ibfk_1', 'pipelines', type_='foreignkey')
    op.drop_constraint(u'pipelines_ibfk_2', 'pipelines', type_='foreignkey')
    op.drop_constraint(u'pipelines_ibfk_3', 'pipelines', type_='foreignkey')
    op.drop_constraint(u'pipelines_ibfk_9', 'pipelines', type_='foreignkey')
    op.drop_constraint(u'pipelines_ibfk_6', 'pipelines', type_='foreignkey')
    op.create_foreign_key(None, 'pipelines', 'tasks', ['init_task_id'], ['id'])
    op.create_foreign_key(None, 'pipelines', 'tasks', ['merge_task_id'], ['id'])
    op.create_foreign_key(None, 'pipelines', 'tasks', ['prun_task_id'], ['id'])
    op.create_foreign_key(None, 'pipelines', 'tasks', ['pre_task_id'], ['id'])
    op.create_foreign_key(None, 'pipelines', 'tasks', ['post_task_id'], ['id'])
    op.create_foreign_key(None, 'pipelines', 'tasks', ['split_task_id'], ['id'])
    op.create_foreign_key(None, 'pipelines', 'tasks', ['finish_task_id'], ['id'])
    op.drop_column('pipelines', 'init_task')
    op.drop_column('pipelines', 'split_task')
    op.drop_column('pipelines', 'post_task')
    op.drop_column('pipelines', 'pre_task')
    op.drop_column('pipelines', 'merge_task')
    op.drop_column('pipelines', 'prun_task')
    op.drop_column('pipelines', 'finish_task')
    op.drop_column('tasks', 'locked')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('locked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('pipelines', sa.Column('finish_task', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pipelines', sa.Column('prun_task', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pipelines', sa.Column('merge_task', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pipelines', sa.Column('pre_task', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pipelines', sa.Column('post_task', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pipelines', sa.Column('split_task', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pipelines', sa.Column('init_task', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pipelines', type_='foreignkey')
    op.drop_constraint(None, 'pipelines', type_='foreignkey')
    op.drop_constraint(None, 'pipelines', type_='foreignkey')
    op.drop_constraint(None, 'pipelines', type_='foreignkey')
    op.drop_constraint(None, 'pipelines', type_='foreignkey')
    op.drop_constraint(None, 'pipelines', type_='foreignkey')
    op.drop_constraint(None, 'pipelines', type_='foreignkey')
    op.create_foreign_key(u'pipelines_ibfk_6', 'pipelines', 'tasks', ['init_task'], ['id'])
    op.create_foreign_key(u'pipelines_ibfk_9', 'pipelines', 'tasks', ['split_task'], ['id'])
    op.create_foreign_key(u'pipelines_ibfk_3', 'pipelines', 'tasks', ['finish_task'], ['id'])
    op.create_foreign_key(u'pipelines_ibfk_2', 'pipelines', 'tasks', ['post_task'], ['id'])
    op.create_foreign_key(u'pipelines_ibfk_1', 'pipelines', 'tasks', ['merge_task'], ['id'])
    op.create_foreign_key(u'pipelines_ibfk_5', 'pipelines', 'tasks', ['pre_task'], ['id'])
    op.create_foreign_key(u'pipelines_ibfk_4', 'pipelines', 'tasks', ['prun_task'], ['id'])
    op.drop_column('pipelines', 'split_task_id')
    op.drop_column('pipelines', 'prun_task_id')
    op.drop_column('pipelines', 'pre_task_id')
    op.drop_column('pipelines', 'post_task_id')
    op.drop_column('pipelines', 'merge_task_id')
    op.drop_column('pipelines', 'init_task_id')
    op.drop_column('pipelines', 'finish_task_id')
    ### end Alembic commands ###